# Generated by Django 5.0.2 on 2024-04-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment_home',
            new_name='PaymentModel',
        ),
    ]
