# Generated by Django 5.0.2 on 2024-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_paymentmodel_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentModel',
        ),
    ]
