# Generated by Django 5.0.2 on 2024-04-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=50)),
                ('nation_id', models.IntegerField()),
            ],
            options={
                'db_table': 'area_table',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=255, null=True)),
                ('package', models.CharField(max_length=255, null=True)),
                ('members', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'user_image',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.packagesmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
