# Generated by Django 5.0.2 on 2024-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
